# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.clccwrergv8l.us-east-1.rds.amazonaws.com/realmeet?&serverTimezone=UTC&useSSL=false
    username: admin
